### ISSUE TITLE
Remove forums, they’re bugged 

### ISSUE THREAD

**Issue by PF94** [squareBracket-and-Finalium/squareBracket#10]
Title says it all

**Comment by forkiesassds** [comment]
![image](https://user-images.githubusercontent.com/54495659/160237179-4ab00efc-7de7-4266-836b-3ef4b2d217b6.png)
Seems to be an issue with prod, not with forums itself.

**Comment by forkiesassds** [comment]
But then again, the forums are a maintainability nightmare, due to the fact it barely uses any templates at all.

**Comment by PF94** [comment]
> But then again, the forums are a maintainability nightmare, due to the fact it barely uses any templates at all.

production website's forums do not load due to template cache issues. we'd be better off removing it.
