### ISSUE TITLE
Replace old squareBracket logos and junk from assets

### ISSUE THREAD

**Issue by Hedy88** [squareBracket-and-Finalium/squareBracket#2]
![image](https://user-images.githubusercontent.com/43907004/159065230-2627800d-27d4-499a-a440-c099a8b868d5.png)

remove junk thanks

**Comment by PF94** [comment]
they can easily be replaced with photoshop (or paint.net if you're poor (or gimp if you're into open source))

**Comment by Kaisiece** [comment]
> or paint.net if you're poor
no!!!
